package com.xg12.entity;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_id
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.no
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    private Integer no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.user_id
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.name
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_id
     *
     * @return the value of t_student.student_id
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_id
     *
     * @param studentId the value for t_student.student_id
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.no
     *
     * @return the value of t_student.no
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.no
     *
     * @param no the value for t_student.no
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.user_id
     *
     * @return the value of t_student.user_id
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.user_id
     *
     * @param userId the value for t_student.user_id
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.name
     *
     * @return the value of t_student.name
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.name
     *
     * @param name the value for t_student.name
     *
     * @mbggenerated Sun Sep 06 08:53:15 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }
}